version: '3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_BACKEND_URL=http://localhost:5001
    ports:
      - "3000:8080"
    environment:
      - VITE_BACKEND_URL=http://localhost:5001
    networks:
      - my_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5001:5000"  # Local port 5001 maps to container port 5000
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

